- hosts: all

  tasks:
   - name: Ansible register variable basic example
     shell: "find *.txt"
     args:
      chdir: "/etc/anexample1"
     register: find_output

   - debug:
      var: find_output

