- hosts: web
  tasks:
   - name: "shut down CentOS 6 and Debian 7 systems"
     command: /etc/ansible/verizon.txt
     when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6") 
